### ISSUE TITLE
Possible to connect sensor directly to arduino?

### ISSUE THREAD

**Issue by burton666** [MaximIntegratedRefDesTeam/OWGridEye#1]
Is is possible to connect the MAXREFDES131# without any additional hardware? How would I need to connect it in that case? And what needs to be modified in the arduino sketches?

**Comment by j3270** [comment]
Hello burton666,

Yes, it is possible, however it requires  bit-banging the 1-Wire interface and currently our 1-Wrie library on Arduino doesn't support that, it may in the future.  For right now, I would recommend acquiring MAXREFDES132 which will work with one of the example programs.

**Comment by horizonful** [comment]
i use arduino uno board，but how do i connect MAXREFDES131 with my arduino ? i don't konw which pin，D3？D4？D5？ and for MAXREFDES131, should i only connect H1 pin1 to VCC，pin2 to GND， and pin3 to Arduino？
thank u~

**Comment by j3270** [comment]
Hello @horizonful,

I recommend the purchase of MAXREFDES132 which has an onboard DS2484 I2C to 1-Wire master and an RJ-11 jack which makes connecting your MAXREFDES131 as simple as plugging in the supplied cable.

Our Arduino library for 1-Wire doesn't support bit-banging the interface.  There is another Arduino library that does, but it doesn't support the DS28E17, or the Grid-EYE.  We have existing examples to help get you started that use the DS2484 on Arduino.

If you don't want to use MAXREFDES132 and want to interface MAXREFDES131 directly to your Arduino via bit-banging.  You will need to review the schematic of MAXREFDES131 and provide your own bit-banging code.

Thanks
