### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by rafaelacardoso** [MaximIntegratedRefDesTeam/OWGridEye#2]
Hi, when I try to upload this FW to my Genuino 101 the following error appears:

In file included from C:\Program Files (x86)\Arduino\libraries\OWGridEye-master\examples\MAXREFDES131_GUI_Firmware\MAXREFDES131_GUI_Firmware.ino:41:0:

C:\Program Files (x86)\Arduino\libraries\OWGridEye-master\src/OWGridEye.h:38:36: fatal error: Slaves/Bridges/Bridges.h: No such file or directory

 #include "Slaves/Bridges/Bridges.h"

                                    ^

compilation terminated.

Can someone help me? 
Thks

**Comment by j3270** [comment]
@rafaelacardoso 

GitHub adds the '-master' extension to the download, you need to remove it from the folder name before adding to your libraries folder.

Additionally, you will need the OneWire library found on this team page.
[https://github.com/MaximIntegratedRefDesTeam/OneWire](url)

**Comment by rafaelacardoso** [comment]
I removed the 'master' and that problem was solved, but now Im getting this messages

_```
In file included from C:\Users\c16492\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.6\system/libarc32_arduino101/common/board.h:42:0,

                 from C:\Users\c16492\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.6\cores\arduino/UARTClass.h:25,

                 from C:\Users\c16492\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.6\variants\arduino_101/variant.h:39,

                 from C:\Users\c16492\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.6\cores\arduino/Arduino.h:109,

                 from sketch\MAXREFDES131_GUI_Firmware.ino.cpp:1:

C:\Users\c16492\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.6\system/libarc32_arduino101/common/misc/util.h:68:14: error: multiple types in one declaration

 #define BOOL int

              ^

C:\Users\c16492\Documents\Arduino\libraries\OWGridEye\src/grideye_api_common.h:11:25: note: in expansion of macro 'BOOL'

 typedef unsigned char   BOOL;

                         ^

C:\Users\c16492\AppData\Local\Arduino15\packages\Intel\hardware\arc32\1.0.6\system/libarc32_arduino101/common/misc/util.h:68:14: error: declaration does not declare anything [-fpermissive]

 #define BOOL int

              ^

C:\Users\c16492\Documents\Arduino\libraries\OWGridEye\src/grideye_api_common.h:11:25: note: in expansion of macro 'BOOL'

 typedef unsigned char   BOOL;

                         ^

C:\Users\c16492\Documents\Arduino\libraries\OWGridEye\examples\MAXREFDES131_GUI_Firmware\MAXREFDES131_GUI_Firmware.ino: In function 'uint8_t init_sensor_state()':

C:\Users\c16492\Documents\Arduino\libraries\OWGridEye\examples\MAXREFDES131_GUI_Firmware\MAXREFDES131_GUI_Firmware.ino:391:64: warning: narrowing conversion of '~(int)write_val' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]

             uint8_t send_block[] = {0x5A, write_val, ~write_val};

                                                                ^

exit status 1
Error compiling for board Arduino/Genuino 101.
```_

Are these problems from my computer? Im sorry to bother you, but I really dont know how to solve this.
Thank you,

**Comment by j3270** [comment]
@rafaelacardoso 

It appears the Arduino IDE is trying to compile for an Intel development board.  Do you have the correct development board selected?  Please navigate to Tools/Board/ and select Arduino/Genuino Uno in the Arduino tool.

You can also try updating your Arduino IDE to the latest version.

Please let me know how it goes, thanks.

**Comment by rafaelacardoso** [comment]
@j3270 Im using an Intel Board, Genuino Uno 101, doesnt it work with the MAXREFDES? I dont have here with me an arduino uno, so I tried to use this intel board, that ir very similar, with the drivers properly installed, but I don't know if this board works with this fw.
I changed my board to Arduino/Genuino Uno and tried the verify button, this appeared:

```
C:\Users\c16492\AppData\Local\Temp\ccxibWO1.ltrans0.ltrans.o: In function OneWire::DS2484::~DS2484()':

C:\Users\c16492\Documents\Arduino\libraries\OneWire\src/Masters/DS248x/DS2484/DS2484.h:68: undefined reference to `operator delete(void*)'

C:\Users\c16492\AppData\Local\Temp\ccxibWO1.ltrans0.ltrans.o: In function `OneWire::DS248x::~DS248x()':

C:\Users\c16492\Documents\Arduino\libraries\OneWire\src\Masters\DS248x/DS248x.h:42: undefined reference to `operator delete(void*)'

C:\Users\c16492\AppData\Local\Temp\ccxibWO1.ltrans0.ltrans.o: In function `__static_initialization_and_destruction_0':

C:\Users\c16492\Documents\Arduino\libraries\OWGridEye\examples\MAXREFDES131_GUI_Firmware/MAXREFDES131_GUI_Firmware.ino:57: undefined reference to `String::String(char const*)'

C:\Users\c16492\AppData\Local\Temp\ccxibWO1.ltrans0.ltrans.o: In function `_GLOBAL__sub_D_rx_str':

C:\Users\c16492\Documents\Arduino\libraries\OWGridEye\examples\MAXREFDES131_GUI_Firmware/MAXREFDES131_GUI_Firmware.ino:57: undefined reference to `String::~String()'

c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/lib/avr5/crtatmega328p.o:(.init9+0x0): undefined reference to `main'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.
```
I'll try to find an Arduino Board to upload the code, but do you thinks is it going to work even with this error message?
Thanks so much for your attention!

**Comment by j3270** [comment]
@rafaelacardoso 

Unfortunately this demo was only tested on an Arduino uno, 8-bit 328p.

Let me see if I can acquire an edison board for testing.

**Comment by j3270** [comment]
@rafaelacardoso 

I just tried the 1.8.3 editor with the  MAXREFDES131_GUI_Firmware and the Arduino/Genuino Uno board, everything was successful.  

Did you edit the code?  

I will try with the 101 board next.

**Comment by j3270** [comment]
Hello @rafaelacardoso,

I just tried the Intel board and received the following;

WARNING: library OneWire claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (arc32) architecture(s).

WARNING: library OWGridEye claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (arc32) architecture(s).

afterwards, I received a similar output to your second post. 

Since Intel discontinued this line of micro, I am not eager to support it.  

Please use the Arduino UNO, or other Arduino with AVR architecture.  

ARM maybe supported in the future and is currently supported on mbed, where this code was originally developed.

https://developer.mbed.org/teams/Maxim-Integrated/code/MAXREFDES131_Qt_Demo/

**Comment by rafaelacardoso** [comment]
Hello @j3270, sorry for the waiting.
I tried it on an Arduino Uno (not a genuino one, being more specific its a DccDuino Uno) and got this messages

```
C:\Users\c16492\Documents\Arduino\libraries\GE_SoftUart\GE_SoftUart.cpp: In function 'void GE_SoftUartRxCallBack()':

C:\Users\c16492\Documents\Arduino\libraries\GE_SoftUart\GE_SoftUart.cpp:15:26: error: 'PIOC' was not declared in this scope

 #define RX_PIN         ((PIOC->PIO_PDSR) & 0x04000000)/* digital pin 4(PC26) */

                          ^

C:\Users\c16492\Documents\Arduino\libraries\GE_SoftUart\GE_SoftUart.cpp:75:10: note: in expansion of macro 'RX_PIN'

      if( RX_PIN )

          ^

C:\Users\c16492\Documents\Arduino\libraries\GE_SoftUart\GE_SoftUart.cpp:15:26: error: 'PIOC' was not declared in this scope

 #define RX_PIN         ((PIOC->PIO_PDSR) & 0x04000000)/* digital pin 4(PC26) */

                          ^

C:\Users\c16492\Documents\Arduino\libraries\GE_SoftUart\GE_SoftUart.cpp:87:6: note: in expansion of macro 'RX_PIN'

   if(RX_PIN)

      ^

C:\Users\c16492\Documents\Arduino\libraries\GE_SoftUart\GE_SoftUart.cpp:93:10: error: 'PIOC' was not declared in this scope

   isr =  PIOC->PIO_ISR;  

          ^

exit status 1
Error compiling for board Arduino/Genuino Uno.
  
```

I think it only works in Arduino/Genuino because of the chip (my arduino uses a USB CH340 Serial Converter instead of the Uno standard Atmega16U2 chip), but I also tried it on Mbed and everything went well, I tested my onewire sensor and it is working.

I'd like to thank you so much for your support, congrats for the great job developing this libraries!
Regards,
